# Default values for home-assistant

namespace: home-assist

image:
  repository: homeassistant/home-assistant
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  ports:
    http: 80
    https: 443
  targetPort: 8123

resources: {}
  # limits:
  #   cpu: 1000m
  #   memory: 1Gi
  # requests:
  #   cpu: 500m
  #   memory: 512Mi

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi
  hostPath: /mnt/data/home-assist
