{{- if .Values.grafana.enabled }}
{{- if not .Values.grafana.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-admin
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.grafana.admin.userKey }}: {{ .Values.grafana.admin.user | b64enc }}
  {{ .Values.grafana.admin.passwordKey }}: {{ .Values.grafana.admin.password | b64enc }}
{{- end }}
{{- end }} 