{{- if and .Values.prometheus.enabled .Values.prometheus.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.prometheus.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size }}
{{- end }} 