{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      serviceAccountName: {{ include "monitoring.fullname" . }}-prometheus
      securityContext:
        fsGroup: 65534  # This is the nobody group, which Prometheus typically runs as
        runAsUser: 65534  # This is the nobody user, which Prometheus typically runs as
        runAsGroup: 65534
        runAsNonRoot: true
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--storage.tsdb.retention.time=15d'
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-storage
              mountPath: /prometheus
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
      volumes:
        - name: prometheus-config
          configMap:
            name: {{ include "monitoring.fullname" . }}-prometheus-config
        {{- if .Values.prometheus.persistence.enabled }}
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: {{ include "monitoring.fullname" . }}-prometheus
        {{- end }}
{{- end }} 