apiVersion: v2
name: homelable
description: Homelable - self-hosted homelab infrastructure visualization, documentation, scanning & live monitoring
type: application
version: 0.1.0
appVersion: "latest"
