apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}
  labels:
    {{- include "nginx-proxy-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.http.port }}
    targetPort: {{ .Values.service.ports.http.targetPort }}
    name: http
  - port: {{ .Values.service.ports.admin.port }}
    targetPort: {{ .Values.service.ports.admin.targetPort }}
    name: admin
  - port: {{ .Values.service.ports.https.port }}
    targetPort: {{ .Values.service.ports.https.targetPort }}
    name: https
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  selector:
    {{- include "nginx-proxy-manager.selectorLabels" . | nindent 4 }} 