{{- range $name, $vol := .Values.persistence }}
{{- if $vol.enabled }}
{{- if $vol.nfs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "nginx-proxy-manager.fullname" $ }}-{{ $name }}-pv
spec:
  capacity:
    storage: {{ $vol.size }}
  accessModes:
    - {{ $vol.accessMode }}
  storageClassName: ""
  nfs:
    server: {{ $vol.nfs.server }}
    path: {{ $vol.nfs.path }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-proxy-manager.fullname" $ }}-{{ $name }}
spec:
  accessModes:
    - {{ $vol.accessMode }}
  storageClassName: {{ $vol.storageClassName | default "" | quote }}
  {{- if $vol.nfs }}
  volumeName: {{ include "nginx-proxy-manager.fullname" $ }}-{{ $name }}-pv
  {{- end }}
  resources:
    requests:
      storage: {{ $vol.size }}
---
{{- end }}
{{- end }}
