apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.redis.repository }}:{{ .Values.image.redis.tag }}"
          imagePullPolicy: {{ .Values.image.redis.pullPolicy }}
          command: ["redis-server", "--bind", "0.0.0.0"]
          ports:
            - containerPort: 6379
