apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.postgres.storageClassName }}
  accessModes:
    - {{ .Values.persistence.postgres.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.postgres.size }}
