apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodata-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.mongodata.storageClassName }}
  accessModes:
    - {{ .Values.persistence.mongodata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mongodata.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redisdata-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.redisdata.storageClassName }}
  accessModes:
    - {{ .Values.persistence.redisdata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.redisdata.size }}
