apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      name: mongo
