apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gotenberg
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-gotenberg
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-gotenberg
    spec:
      containers:
        - name: gotenberg
          image: "{{ .Values.gotenberg.image.repository }}:{{ .Values.gotenberg.image.tag }}"
          imagePullPolicy: {{ .Values.gotenberg.image.pullPolicy }}
          args:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"
          ports:
            - containerPort: 3000
