apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tika
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-tika
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-tika
    spec:
      containers:
        - name: tika
          image: "{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag }}"
          imagePullPolicy: {{ .Values.tika.image.pullPolicy }}
          ports:
            - containerPort: 9998
