apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: paperless-ngx
          image: "{{ .Values.paperless.image.repository }}:{{ .Values.paperless.image.tag }}"
          imagePullPolicy: {{ .Values.paperless.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_CONSUMPTION_DIR
              value: {{ .Values.paperless.mountPaths.consume }}
            - name: PAPERLESS_MEDIA_ROOT
              value: {{ .Values.paperless.mountPaths.mediaData }}/media
            - name: PAPERLESS_DATA_DIR
              value: {{ .Values.paperless.mountPaths.mediaData }}/data
            - name: PAPERLESS_REDIS
              value: "redis://{{ .Release.Name }}-redis:6379"
            - name: PAPERLESS_DBHOST
              value: "{{ .Release.Name }}-postgres"
            - name: PAPERLESS_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: POSTGRES_DB
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: POSTGRES_USER
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PAPERLESS_TIKA_ENABLED
              value: "1"
            - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
              value: "http://{{ .Release.Name }}-gotenberg:3000"
            - name: PAPERLESS_TIKA_ENDPOINT
              value: "http://{{ .Release.Name }}-tika:9998"
            {{- range $key, $value := .Values.paperless.env }}
            - name: {{ $key }}
              {{- if kindIs "string" $value }}
              value: {{ $value | quote }}
              {{- else }}
              {{- toYaml $value | nindent 14 }}
              {{- end }}
            {{- end }}
          volumeMounts:
            - name: mediaData
              mountPath: {{ .Values.paperless.mountPaths.mediaData }}
            - name: consume
              mountPath: {{ .Values.paperless.mountPaths.consume }}
      volumes:
        - name: mediaData
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mediaData-pvc
        - name: consume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-consume-pvc
