---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mediaData-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.mediaData.storageClassName }}
  accessModes:
    - {{ .Values.persistence.mediaData.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.mediaData.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-consume-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.consume.storageClassName }}
  accessModes:
    - {{ .Values.persistence.consume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.consume.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pgdata-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.pgdata.storageClassName }}
  accessModes:
    - {{ .Values.persistence.pgdata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.pgdata.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redisdata-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.redisdata.storageClassName }}
  accessModes:
    - {{ .Values.persistence.redisdata.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.redisdata.size }}
