apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: cloudflared
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.cloudflared.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: cloudflared
