image:
  repository: jc21/nginx-proxy-manager
  tag: 2.13.5
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  ports:
    http:
      port: 80
      targetPort: 80
    admin:
      port: 81
      targetPort: 81
    https:
      port: 443
      targetPort: 443
  loadBalancerIP: 192.168.100.14

# Persistence volumes. Two modes:
#
# NFS (manual PV):
#   storageClassName: ""
#   nfs:
#     server: my-nas.example.com
#     path: /volume1/some/path
#
# Dynamic storage class (e.g. longhorn):
#   storageClassName: longhorn
#   # omit the nfs block entirely
persistence:
  data:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    storageClassName: longhorn
  letsencrypt:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClassName: longhorn
# persistence:
#   data:
#     enabled: true
#     size: 10Gi
#     accessMode: ReadWriteMany
#     storageClassName: ""
#     nfs:
#       server: nas-alpha.example.net
#       path: "/volume1/tpi-k3s/nginx-proxy-manager/data"
#   letsencrypt:
#     enabled: true
#     size: 5Gi
#     accessMode: ReadWriteMany
#     storageClassName: ""
#     nfs:
#       server: nas-alpha.example.net
#       path: "/volume1/tpi-k3s/nginx-proxy-manager/letsencrypt"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi
