# Storage classes for home infrastructure
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
