apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thechart.fullname" . }}-config
  labels:
    {{- include "thechart.labels" . | nindent 4 }}
data:
  config.yml: |
    server:
      url: {{ .Values.emby.protocol }}://{{ .Values.emby.url }}
      port: {{ .Values.emby.port }}
      userID: {{ .Values.emby.userId }}
      token: {{ .Values.emby.apikey }}

