services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9925:9000"
    volumes:
      - /volume1/mealie:/app/data
    environment:
      ALLOW_SIGNUP: "false"
      PUID: "1000"
      PGID: "1000"
      TZ: "America/New_York"
      MAX_WORKERS: "1"
      WEB_CONCURRENCY: "1"
      BASE_URL: "https://mealie.example.net"
