apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  settings.yaml: |
    {{- .Values.config.settings | nindent 4 }}
  kubernetes.yaml: |
    {{- .Values.config.kubernetes | nindent 4 }}
  bookmarks.yaml: |
    {{- .Values.config.bookmarks | nindent 4 }}
  services.yaml: |
    {{- .Values.config.services | nindent 4 }}
  widgets.yaml: |
    {{- .Values.config.widgets | nindent 4 }}
  docker.yaml: |
    {{- .Values.config.docker | nindent 4 }}
  custom.css: |
    {{- .Values.config.customCss | nindent 4 }}
  custom.js: |
    {{- .Values.config.customJs | nindent 4 }}
