apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microk8s-nfs-nas-beta-provisioner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    chart: nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      values: |
        nfs:
          server: 192.168.1.180
          path: /mnt/user/tpi_k3s

        storageClass:
          name: nfs-nas-beta
          provisionerName: cluster.local/nfs-nas-beta-provisioner
          defaultClass: false
          accessModes: ReadWriteMany
          reclaimPolicy: Delete
          archiveOnDelete: true
  destination:
    server: https://192.168.1.170:16443
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
