apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com/nmcglo/home-infra.git
    targetRevision: HEAD  # Uses default branch
    path: kubernetes/apps/paperless-ngx
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless-ngx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
