apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rk-llamacpp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com/nmcglo/home-infra.git
    targetRevision: HEAD
    path: kubernetes/apps/rk-llama.cpp-server
  destination:
    server: https://kubernetes.default.svc
    namespace: rk-llamacpp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
