apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@forgejo.example.net:nmcglo/home-infra.git
    targetRevision: HEAD  # Uses default branch
    path: kubernetes/apps/stirling-pdf
  destination:
    server: https://kubernetes.default.svc
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
