{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            {{- range .Values.onepasswordSecrets }}
            {{- if .enabled }}
            {{- $secretName := .name }}
            {{- range .env }}
            - name: {{ .envVar }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .secretKey }}
            {{- end }}
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
{{- end }}
