apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent-exporter.fullname" . }}
  labels:
    {{- include "qbittorrent-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qbittorrent-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qbittorrent-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: QBITTORRENT_HOST
              value: {{ .Values.qbittorrent.host | quote }}
            - name: QBITTORRENT_PROTOCOL
              value: {{ .Values.qbittorrent.protocol | quote }}
            - name: QBITTORRENT_PORT
              value: {{ .Values.qbittorrent.port | quote }}
            - name: QBITTORRENT_USERNAME
              value: {{ .Values.qbittorrent.username | quote }}
            - name: QBITTORRENT_PASSWORD
              value: {{ .Values.qbittorrent.password | quote }}
          ports:
            - name: http
              containerPort: 17871
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 