{{- range .Values.onepasswordSecrets }}
{{- if .enabled }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: {{ $.Release.Name }}
  annotations:
    operator.1password.io/auto-restart: {{ .autoRestart | default "false" | toString | quote }}
spec:
  itemPath: {{ .itemPath | quote }}
{{- end }}
{{- end }}
