---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- if and (eq .Values.database.type "postgres") .Values.database.postgres.internal }}
{{- $pgdata := default dict .Values.persistence.pgdata }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pgdata-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ $pgdata.storageClassName | default "longhorn" }}
  accessModes:
    - {{ $pgdata.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $pgdata.size | default "10Gi" }}
{{- end }}
