{{- $hasSecretKey := kindIs "string" .Values.forgejo.config.security.secretKey }}
{{- $hasDbPasswd := and (eq .Values.database.type "postgres") (kindIs "string" .Values.database.postgres.password) }}
{{- if or $hasSecretKey $hasDbPasswd }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- if $hasSecretKey }}
  FORGEJO__SECURITY__SECRET_KEY: {{ .Values.forgejo.config.security.secretKey | quote }}
  {{- end }}
  {{- if $hasDbPasswd }}
  FORGEJO__DATABASE__PASSWD: {{ .Values.database.postgres.password | quote }}
  {{- end }}
{{- end }}
{{- if and (eq .Values.database.type "postgres") .Values.database.postgres.internal (kindIs "string" .Values.database.postgres.password) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.database.postgres.password | quote }}
{{- end }}
