apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
    {{- if and .Values.service.ssh.enabled (not .Values.forgejo.config.server.disableSsh) }}
    - name: ssh
      protocol: TCP
      port: {{ .Values.service.ssh.port }}
      targetPort: {{ .Values.service.ssh.targetPort }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
