apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        supplementalGroups:
          - 44
          - 992
      initContainers:
        - name: fix-freq
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/rkllama-cpp/fix_freq_rk3588.sh"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys
              mountPath: /sys
      containers:
        - name: rk-llamacpp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          securityContext:
            privileged: true
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: models
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        {{- if .Values.persistence.enabled }}
        - name: models
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-models-pvc
        {{- end }}
