apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: adguard-home-sync
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - run
            - --config
            - /config/adguardhome-sync.yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.ports.http.targetPort }}
              protocol: TCP
          {{- if .Values.onepasswordSecrets }}
          env:
          {{- range .Values.onepasswordSecrets }}
          {{- if .enabled }}
          {{- $secretName := .name }}
          {{- range .env }}
            - name: {{ .envVar }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .secretKey }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
