apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  {{- range $key, $port := .Values.service.ports }}
  - protocol: {{ $port.protocol }}
    port: {{ $port.port }}
    targetPort: {{ $port.targetPort }}
    name: {{ $key }}
  {{- end }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.type | eq "LoadBalancer" }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
